### ISSUE TITLE
SPARQL IRI function does not work

### ISSUE THREAD

**Issue by TBoonX** [SmartDataAnalytics/RdfProcessingToolkit#28]
Running the jena-4.6.0 branch rpt, the IRI function does not return something.

`IRI("http://example/")` does not create an IRI.

Example:
```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

construct {
  <http://example.com/12>
    rdfs:seeAlso ?a .
}
where {
  bind(IRI("http://example/111") as ?a)
}

```

There is no error.

**Comment by Aklakan** [comment]
The problem was introduced by https://github.com/apache/jena/issues/1272

RPT used to use an empty base URL to retain relative IRIs - however the fix for the issue above now rejects ANY relative base IRI in the iri function.

`iri:asGiven("http://foo")"` is the ugly workaround for now :/
(the iri namespace is implicitly available any resolve to `http://jsa.aksw.org/fn/iri`.

**Comment by SimonBin** [comment]
this is fixed now right?

**Comment by Aklakan** [comment]
Yes, its fixed. RPT no longer uses an empty base URL hack but instead by default uses an absolute file URL to the current working directory. 
```
/tmp$ rpt integrate 'IRI("http://example/") {}' --out-format csv
# file:///tmp/example/
```

The rationale for this is to allow for out-of-the-box simple relative references to files such as  `<myfolder/data.csv> csv:parse ?row`.

The recommendation is to use `iri:asGiven` explicitly when needed. Also, with `ExprTransformIriToIriAsGiven` we have a transformer that can replace all IRI expressions with `iri:asGiven` when desired. This way we can transparently change the semantics of IRI to (a) allow for relative IRIs without having to alter Jena ARQ's standard SPARQL machinery and (b) avoid the expensive IRI validation.
