### ISSUE TITLE
integrate shows strange behavior when JSON-LD is used

### ISSUE THREAD

**Issue by TBoonX** [SmartDataAnalytics/RdfProcessingToolkit#29]
Command:

`java -jar $PATH_RPT integrate -o=local_licenses.jsonld --out-format=jsonld datasources.n3 get_licenses.rq`

Version: 1.9.1

datasources.n3:
```
<http://dalicc.net/dependencygraph/dg_default/>
        <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  <https://vocab.eccenca.com/di/Dataset> .

<https://coypu.org/datasource/COY%20Ontology%20%2F%20CoyPu%20Schema> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/dcat#Dataset>.
<https://coypu.org/datasource/COY%20Ontology%20%2F%20CoyPu%20Schema> <http://purl.org/dc/terms/title> "COY Ontology / CoyPu Schema".
<https://coypu.org/datasource/COY%20Ontology%20%2F%20CoyPu%20Schema> <http://purl.org/dc/terms/language> "http://id.loc.gov/vocabulary/iso639-1/en".
<https://coypu.org/datasource/COY%20Ontology%20%2F%20CoyPu%20Schema> <http://purl.org/dc/terms/license> <http://dalicc.net/licenselibrary/CC-BY_v4>.
```

get_licenses.rq:
```
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX odrl: <http://www.w3.org/ns/odrl/2/>
construct { ?license a odrl:Set . }
 WHERE {
   SELECT distinct ?license WHERE {
     ?ds a <http://www.w3.org/ns/dcat#Dataset> ;
     dcterms:license ?license .
   }

}

```

It shows an RDF result in the terminal, but writes `[]` into the jsonld file. With other formats it works.

**Comment by Aklakan** [comment]
One part of the issue seems to be that there is no streaming json ld writer in jena. The code is adapted that streaming formats now fall back to non-streaming serialization.

A useful improvement now would be writing out a log message whether streaming or non-streaming is used - not yet sure about how to handle this; e.g. the sink could either expose a flag or a more general set of capabilities.

**Comment by Aklakan** [comment]
A release candidate with the jsonld fix (and the latest jenax plugins) has been created at https://github.com/SmartDataAnalytics/RdfProcessingToolkit/releases/tag/v1.9.2-rc1

**Comment by TBoonX** [comment]
Works with RC1.

**Comment by Aklakan** [comment]
A couple of issues
* Using `--out-format json` (instead of `--out-format jsonld`) only writes out an empty json array `[]` (which might be easily mistaken for a blank node). The reason is that the `json` format is only internally used if the `--jq` switch is present . This is somewhat confusing.
* Conversely, using `--jq` and `--out-file` unexpectedly requires to specify `--out-format json`
